<?php
    return [
        'products' => [
            'name' => 'Tên khóa học',
            'sub_name' => 'Slogan',
            'description' => 'Mô tả',
            'images' => 'Hình ảnh',
            'start_date' => 'Ngày bắt đầu',
            'block_1_title' => 'Tiêu đề block 1',
            'block_2_title' => 'Tiêu đề block 2',
            'block_3_title' => 'Tiêu đề block 3',
            'block_1_image' => 'Hình ảnh block 1',
            'block_2_image' => 'Hình ảnh block 2',
            'block_3_image' => 'Hình ảnh block 3',
            'block_1_content' => 'Nội dung block 1',
            'block_2_content' => 'Nội dung block 2',
            'block_3_content' => 'Nội dung block 3',
            'free_price' => 'Giá gói Free',
            'basic_price' => 'Giá gói Basic',
            'premium_price' => 'Giá gói Premium',
            'free_benefit' => 'Lợi ích gói Free',
            'basic_benefit' => 'Lợi ích gói Basic',
            'pre_benefit' => 'Lợi ích gói Premium',
            'comments' => 'Nhận xét học viên',
            'teacher' => 'Nghệ sĩ',
            'status' => 'Trạng thái',
            'color' => 'Background',
        ],
        'artists' => [
            'name' => 'Họ và tên',
            'email' => 'Email',
            'images' => 'Hình ảnh',
            'banner' => 'Banner',
            'profile' => 'Profile',
            'clubs' => 'Club đã hợp tác',
            'partners' => 'Nghệ sĩ đã hợp tác',
            'project_1_title' => 'Title project 1',
            'project_1_image' => 'Hình ảnh project 1',
            'project_1_text' => 'Nội dung project 1',
            'project_2_title' => 'Title project 2',
            'project_2_image' => 'Hình ảnh project 2',
            'project_2_text' => 'Nội dung project 2',
            'project_3_title' => 'Title project 3',
            'project_3_image' => 'Hình ảnh project 3',
            'project_3_text' => 'Nội dung project 3',
            'bts_text' => 'BTS title',
            'bts_image' => 'BTS Hình ảnh',
            'bts_link_yt' => 'Link Youtube',
            'bts_link_ins' => 'Link Instagram',
            'bts_link_fb' => 'Link Facebook',
            'bts_link_tt' => 'Link TikTok',
            'bts_link_sc' => 'Link Soundcloud',
            'life_style_1' => 'Ảnh lifestyle 1',
            'life_style_2' => 'Ảnh lifestyle 2',
            'life_style_3' => 'Ảnh lifestyle 3',
            'life_style_4' => 'Ảnh lifestyle 4',
            'life_style_5' => 'Ảnh lifestyle 5',
            'life_style_6' => 'Ảnh lifestyle 6',
        ],
        'students' => [
            'name' => 'Họ và tên',
            'select_student' => 'Chọn học viên',
            'opinion_student' => 'Ý kiến học viên',
            'comments' => 'Bình luận',
            'class_id' => 'Lớp học',
            'thumbnail' => 'Hình ảnh',
        ]
    ];